services:
  bots:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    command: ["poetry", "run", "python", "app.py"]
    profiles:
      - full

  postgres:
    image: 'postgres:17.2'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: bot
    profiles:
      - full
      - infrastructure
      - without_bot

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    profiles:
      - full
      - infrastructure
      - without_bot

  service-qr:
    build:
      context: ./service-qr
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    profiles:
      - full
      - without_bot
